=== sabasazad/XmlCookbook/recipes.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="time" type="xs:nonNegativeInteger"/>
<xs:element name="unit" type="xs:string"/>
<xs:element name="amount" type="xs:string"/>
<xs:element type="xs:string" name="description"/>
<xs:element type="xs:string" name="title"/>
<xs:element 	name="GRAPHIC">
  <xs:complexType>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute  name="url" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:element>


  <xs:element name="cookbook">
    <xs:annotation>
      <xs:documentation>Sample XML file generated by XMLSpy v2021 rel. 3 (x64) (http://www.altova.com)</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
       <xs:element ref="description"/>
        <xs:element name="recipe" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="title"/>
              <xs:element ref="GRAPHIC"/>
		          <xs:element  name="course" type="xs:string"/>
			 
			 <xs:element name="cuisine" >
				<xs:complexType>
				<xs:attribute name="type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
							<xs:enumeration value="American"/>
							<xs:enumeration value="Mexican" />
							<xs:enumeration value="French" />
							<xs:enumeration value="Italian" />
					</xs:restriction>
				</xs:simpleType>
				</xs:attribute>
				</xs:complexType>
			</xs:element>
			  
			  
			  
             <xs:element name="ingredients">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ingredient" maxOccurs="unbounded" minOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element  name="name" 		type="xs:string"/>
                          <xs:element  name="amount" 	type="xs:string"/>
                          <xs:element  ref="unit"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
			  
			  
              <xs:element name="preparation">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="step" maxOccurs="unbounded" minOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
			  
              <xs:element name="nutrition">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element  name="protein"> 
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element ref="amount"/><xs:element ref="unit"/>
                         </xs:sequence>
                      </xs:complexType>
                    </xs:element>
					           <xs:element  name="carbohydrates">
					             <xs:complexType>
					               <xs:sequence>
					                 <xs:element ref="amount"/><xs:element ref="unit"/>
					               </xs:sequence>
					             </xs:complexType>
					           </xs:element> 
                    
                    <xs:element  name="fat">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element ref="amount"/><xs:element ref="unit"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element> 
                    
                    <xs:element  name="calories" type="xs:nonNegativeInteger"/>
                               
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
			  
			  		  
            <xs:element name="preptime">
					<xs:complexType>
					<xs:sequence>
						<xs:element ref="time"/>
						<xs:element ref="unit"/>
					</xs:sequence>
					</xs:complexType> 
				</xs:element>
				
			<xs:element name="cooktime">
					<xs:complexType>
					<xs:sequence>
						<xs:element ref="time"/>
						<xs:element ref="unit"/>
					</xs:sequence>
					</xs:complexType> 
				</xs:element>	
			
			<xs:element name="totaltime">
					<xs:complexType>
					<xs:sequence>
						<xs:element ref="time"/>
						<xs:element ref="unit"/>
					</xs:sequence>
					</xs:complexType> 
				</xs:element>			
              
            <xs:element  name="comment"   type="xs:string"/>
			              
            

          </xs:sequence>
          <xs:attribute name="recipeid" type="xs:string" /> 
      </xs:complexType>
        </xs:element>
      </xs:sequence>
    
    </xs:complexType>
  </xs:element>
</xs:schema>

=== sabasazad/XmlCookbook/Recipes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2021 rel. 3 (x64) (http://www.altova.com)-->
<?xml-stylesheet href="recipes.xsl" type="text/xsl"?>
<cookbook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="recipes.xsd">
  <description>Some recipes for the cookbook.</description>
  <recipe recipeid="1">
    <title>White Pasta with Beef</title>
    <GRAPHIC url="images/white-pasta-with-beef.jpg"/>
    <course>Main</course>
    <cuisine type = "American"></cuisine>
    <ingredients>
      <ingredient>
        <name>ground beef</name>
        <amount>1/2</amount>
        <unit>pound</unit>
      </ingredient>
      <ingredient>
        <name>penne pasta</name>
        <amount>2</amount>
        <unit>cup</unit>
      </ingredient>
      <ingredient>
        <name>vegetable broth</name>
        <amount>2</amount>
        <unit>cup</unit>
      </ingredient>
      <ingredient>
        <name>onion</name>
        <amount>1/2</amount>
        <unit></unit>
      </ingredient>
      <ingredient>
        <name>water</name>
        <amount>2 and 1/2</amount>
        <unit>cup</unit>
      </ingredient>
      <ingredient>
        <name>basil (chopped)</name>
        <amount>1/2</amount>
        <unit>cup</unit>
      </ingredient>
      <ingredient>
        <name>garlic clove</name>
        <amount>1</amount>
        <unit></unit>
      </ingredient>
      <ingredient>
        <name>ground black pepper</name>
        <amount>1/8</amount>
        <unit>teaspoon</unit>
      </ingredient>
      <ingredient>
        <name>cooking spray</name>
        <amount></amount>
        <unit></unit>
      </ingredient>
      <ingredient>
        <name>cream cheese</name>
        <amount>4</amount>
        <unit>ounce</unit>
      </ingredient>
      <ingredient>
        <name>lemon</name>
        <amount>1</amount>
        <unit></unit>
      </ingredient>
      <ingredient>
        <name>grated parmesan cheese</name>
        <amount>1/2</amount>
        <unit>cup</unit>
      </ingredient>
    </ingredients>
    <preparation>
      <step>Add uncooked pasta, water, and broth to a large stockpot. Slice onion and add to pot along with basil, minced garlic,      salt, and pepper. Cover and cook on medium-high, bringing to a boil. Remove cover and cook for 8-10 minutes or until liquid has completely absorbed, stirring occasionally.</step>
      <step>Meanwhile, spray a skillet with cooking spray and heat over medium. Add beef and cook until browned, stirring to 			 	crumble.	</step>
      <step>Add beef to cooked pasta. Stir in cream cheese, 2-3 tablespoons of fresh lemon juice, zest of lemon, and Parmesan 	  cheese.		</step>
      <step>Serve with orange wedges on the side.</step>
    </preparation>
    
    <nutrition>
        
      <protein><amount>28</amount><unit>g</unit></protein>
      <carbohydrates><amount>63</amount><unit>g</unit></carbohydrates>
      <fat><amount>11</amount><unit>g</unit></fat>
      <calories>458</calories>
   
    </nutrition>
    
    <preptime><time>15</time><unit>minutes</unit></preptime>
    <cooktime><time>20</time><unit>minutes</unit></cooktime>
    <totaltime><time>35</time><unit>minutes</unit></totaltime>
    <comment>A healthy and yummy recipe for dinner for kids, who are picky eaters.</comment>
  </recipe>
  
  <recipe recipeid="2">
    <title>Chicken and Brown Rice</title>
    <GRAPHIC url="images/chicken-with-brown-rice.jpg"/>
    <course>Main</course>
    <cuisine type = "American"></cuisine>
    <ingredients>
      <ingredient>
        <name>onion</name>
        <amount>1</amount>
        <unit>medium</unit>
      </ingredient>
      <ingredient>
        <name>garlic</name>
        <amount>3</amount>
        <unit>clove</unit>
      </ingredient>
      <ingredient>
        <name>carrots, baby</name>
        <amount>2</amount>
        <unit>cup</unit>
      </ingredient>
      <ingredient>
        <name>mushrooms, brown, italian or Crimini</name>
        <amount>2</amount>
        <unit>cup</unit>
      </ingredient>
      <ingredient>
        <name>olive oil</name>
        <amount>1</amount>
        <unit>tablespoon</unit>
      </ingredient>
      <ingredient>
        <name>chicken broth</name>
        <amount>2 1/4</amount>
        <unit>cup</unit>
      </ingredient>
      <ingredient>
        <name>chicken thigh, boneless, skinless</name>
        <amount>2</amount>
        <unit>pound</unit>
      </ingredient>
	  <ingredient>
        <name>salt</name>
        <amount>1/8</amount>
        <unit>teaspoon</unit>
      </ingredient>
      <ingredient>
        <name>ground black pepper</name>
        <amount>1/8</amount>
        <unit>teaspoon</unit>
      </ingredient>
      <ingredient>
        <name>soup, cream of chicken, canned, condensed</name>
        <amount>10.75</amount>
        <unit>ounce</unit>
      </ingredient>
      <ingredient>
        <name>Worcestershire sauce</name>
        <amount>2</amount>
        <unit>tablespoon</unit>
      </ingredient>
      <ingredient>
        <name>thyme, fresh</name>
        <amount>1</amount>
        <unit>tablespoon</unit>
      </ingredient>
    </ingredients>
    <preparation>
      <step>Push “saute” button on Instant Pot. While it heats, dice onion, mince garlic, and chop veggies. Rinse and drain rice. </step>
      <step>When pot says “HOT,” add oil to pot and saute onions for 3 minutes. Then press “cancel” to turn the saute setting off.	</step>
      <step>Mix veggies, garlic, rice, and broth into the pot. Place chicken on top, salt and pepper, then cover with cream of chicken soup (homemade is preferable) and Worchestershire sauce. Place 8-10 small sprigs of thyme on top. NOTE: chicken breasts also work well, just make sure to cut them in half so they’re not too thick.	</step>
      <step>Seal the Instant Pot, close the vent, and press “manual.” Use the “pressure” button to toggle to high pressure.  For brown rice: set the time for 25 minutes.  For white rice: set the timer for 20 minutes.  After 10 seconds the pot should register that it has begun the pressurizing process.</step>
	  <step>Once the pot is done cooking open the vent (keep your hand out of the path of the steam) to quick release the pressure.  This should take about 2 minutes.  Once pressure has released completely (the pin drops) the pot is safe to open.</step>
	  <step>Remove thyme sprigs (keeping leaves when possible). Stir pot to shred chicken and mix in any extra liquid. Serve warm.</step>
	</preparation>
    
    <nutrition>
        
      <protein><amount>28</amount><unit>g</unit></protein>
      <carbohydrates><amount>47</amount><unit>g</unit></carbohydrates>
      <fat><amount>10</amount><unit>g</unit></fat>
      <calories>387</calories>
   
    </nutrition>
    
    <preptime><time>5</time><unit>minutes</unit></preptime>
    <cooktime><time>54</time><unit>minutes</unit></cooktime>
    <totaltime><time>59</time><unit>minutes</unit></totaltime>
    <comment>It’s delicious and comforting. If creamy, savory rice, flavorful veggies, and fall-apart tender chicken sound like your thing, you should try this recipe.</comment>
 
  </recipe>
  
  <recipe recipeid="3">
    <title>Breakfast Egg Cups</title>
    <GRAPHIC url="images/breakfast-egg-cups.jpg"/>
    <course>Breakfast</course>
    <cuisine type = "American"></cuisine>
    <ingredients>
      <ingredient>
        <name>egg</name>
        <amount>6</amount>
        <unit>large</unit>
      </ingredient>
      <ingredient>
        <name>milk</name>
        <amount>1/4</amount>
        <unit>cup</unit>
      </ingredient>
      <ingredient>
        <name>salt</name>
        <amount>1/8</amount>
        <unit>teaspoon</unit>
      </ingredient>
      <ingredient>
        <name>ground black pepper</name>
        <amount>1/8</amount>
        <unit>teaspoon</unit>
      </ingredient>
      <ingredient>
        <name>bell pepper, red</name>
        <amount>1</amount>
        <unit>medium</unit>
      </ingredient>
      <ingredient>
        <name>Spinach</name>
        <amount>3/4</amount>
        <unit>cup</unit>
      </ingredient>
      <ingredient>
        <name>cheddar cheese</name>
        <amount>1</amount>
        <unit>ounce</unit>
      </ingredient>
	  <ingredient>
        <name>cooking spray</name>
        <amount>1</amount>
        <unit></unit>
      </ingredient>
    </ingredients>
    <preparation>
		<step>Spray a muffin tin with cooking spray and  set aside. Preheat oven to 375°F.</step>
		<step>Whisk the eggs and milk together in a bowl. Season with salt and pepper.</step>
		<step>Dice the bell pepper into small pieces. Stack the spinach leaves, roll them up, and slice them thin. (This method is called chiffonade.)</step>
		<step>Add the peppers, spinach, and shredded cheddar to the egg mixture.</step>
		<step>Fill muffin cups 3/4 full and bake for 20-25 minutes until centers are set and no longer runny.</step>
		<step>Allow to cool slightly before serving.</step>
	  </preparation>
    
    <nutrition>
        
      <protein><amount>6</amount><unit>g</unit></protein>
      <carbohydrates><amount>2</amount><unit>g</unit></carbohydrates>
      <fat><amount>5</amount><unit>g</unit></fat>
      <calories>78</calories>
   
    </nutrition>
    
    <preptime><time>10</time><unit>minutes</unit></preptime>
    <cooktime><time>25</time><unit>minutes</unit></cooktime>
    <totaltime><time>35</time><unit>minutes</unit></totaltime>
    <comment>This recipe is the perfect breakfast on-the-go. Make them ahead of time, refrigerate or freeze them, and then heat them in the microwave when you are ready to eat!</comment>
  </recipe>
  
</cookbook>
